spring:
  application:
    name: jeecg-system
  profiles:
    active: '@profile.name@'
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
login:
  web:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCxGJm1AmuCpuF4FAqM6IS5SOZCKzPBJaPG6raFCvseZUx/53K5jHEbiwVJN5NMgh/BuZ2TTgmQPIDJHHACIcgDOXzd6Zx0yxSik/q1L9575vKlhkljtmexlYakcKtHt1bK2qKyK0fJNq+HJNT0vN8w0PNKglDVRuJKVL2ottS4xQIDAQAB
    private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALEYmbUCa4Km4XgUCozohLlI5kIrM8Elo8bqtoUK+x5lTH/ncrmMcRuLBUk3k0yCH8G5nZNOCZA8gMkccAIhyAM5fN3pnHTLFKKT+rUv3nvm8qWGSWO2Z7GVhqRwq0e3VsraorIrR8k2r4ck1PS83zDQ80qCUNVG4kpUvai21LjFAgMBAAECgYAG/bofp6331T+vCQIrnYg+dO7GFkTaRJ1KXnyrFDZlSklyqSqMbEtmHh8CIhlaBVmx650ZXL91kWCMz+cUu8xUp0OjrvyPqMVed7Px1yzpv6kKuJoAKiAWgUT/VKG9TNOtEu9GXA3nkkm//AI8tn92TwdzXbb6MojcniUt2G911wJBALfV1w3syDFJG/LQ9umh+NBlcTcJHAgH1qF1yuz4jeNj5JIgB2DcYmAna5ju4q3eKgVZTcSp1/Q77XKI5oOso4MCQQD2nYQqcVJCc9DvD9SgCpU0hWpfHFF/agjDy2S1LsQx0lrV16cMKYFN9ybmbrcIzWTQq/k6bVwh2F3wOkSJ31gXAkEAlRsYxu6aoX8O8C+VVYJOcZkV7vGwjsLszyDfar1fOGQ5bFwWH/YgxKS0nOKFcUiVBKmebjjkM/C3cwKfFYXdSQJBAN1sC/B3kp3rkpoyInwXRGPFrf37VQkLURdKlP9AIBODhN8fIvL+iQRRdfHLUjdrAquA3OKisegJdj5scoE/sL0CQEEEUrmRMXvPSizf9HtkUQ7HR31CYICj4CD2tE1SJYYBT0Al/nO2ib8THNRy+09B56GGpiCbi+84720zygkgsdg=
  miniapp:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCWxdLGzSNeR+P+HlSPEK6Ib7ywAe+Bb9vadCrUs2vXZPhdMF66EkbCQ54VKr7UapjdhyD+pQu1Z7pUePFDW6367kR0SWNlXkIJ7bc+jSUods19G4UE67k0YW3IlViD6VI/Vyhj63flynaz8Ne6Q+gU3vRFLPXhzQ76m4raMa1LQwIDAQAB
    private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJbF0sbNI15H4/4eVI8QrohvvLAB74Fv29p0KtSza9dk+F0wXroSRsJDnhUqvtRqmN2HIP6lC7VnulR48UNbrfruRHRJY2VeQgnttz6NJSh2zX0bhQTruTRhbciVWIPpUj9XKGPrd+XKdrPw17pD6BTe9EUs9eHNDvqbitoxrUtDAgMBAAECgYBKdierLBvID8wvL+6F+3CfDEQNTt9otwRG5rFSe8wKRCEO8PkPf0A35+oWPRai1IRrf7WRXZSjQje5SUOqBwisSgAvr3tZjPheRaa/+K8GCv8ilwKqGYiAoKiDi/rHAta3NuhrU+9NgaaOyJUJMzVKKaM/geZJYVIbufcpqFNlEQJBAPhaUZnnum5ckvGaYYrqk0ykI8rqES4DFd+ssC3pQF4i6xprzObPX62sxRQcUYE8ZP+lfHW3kGbnSBN0kE5b49ECQQCbalBfdJKd+Kaur/UoG2frMn3R0cBpTytCbzIZCrgu0SSyXkzJGnSZ9Go/eoKgUPKBdplQQrOW77vlT+5zh6bTAkBLrSnkXeo/KtJT8Jj8fZI47mNBt6VYgfQuXi6pLsRAax98w5CCXHppL5Y2FJL5cG/OPpz4OeE0mhEqbIB0gCehAkEAlYgk7LLsnrGvLkR+TKiRw+pAxLBbwPc7WCBEw3Nc4y63cCbrGlMp/Tb9QzZMmJNJwOarfF2xDXh8AJZ3hxDtoQJBANYso3RojysvATu3ygmhOc+UY9XGIzS1B/xQP6ek4wuACby+Jj/HYgMNL5hqJSXHkoilaS5vaJkD3MvzQmBAzTY=
